##########################################################################################
## Simulate multivariate normal data, partition it, and synthesize the partitions,      ##
## then, bind the synthetic partitions and analyse it                                   ##
##########################################################################################

## Source the completed boys data, and source the functions file
source("1.a Create data - boys complete.R")
source("1.c Functions.R")

## Load the required packages, furrr for parallel map functions, tidyverse for tidy data,
## synthpop for data synthesis
library(furrr)
library(tidyverse)
library(synthpop)

## Specify that we run the code in multiple sessions, to speed up the process
plan(multisession)

## Set the number of simulations
nsim <- 1000

## Specify the input for the multivariate normal data sampling
r2 <- .5                    # R2 of .5
ratio <- c(0,1,2)           # Uninformative predictor and two informative predictors
rho <- diag(length(ratio))  # Uncorrelated predictors
n1 <- 100                   # Sample size
                            
# real_coefs are the population regression coefficients
real_coefs <- normal(r2,ratio,rho,n1)$coefs

# f is the formula of the linear regressions during the rest of the code
f <- DV ~ -1 + IV1 + IV2 + IV3

##########################################################################################
## First, we use the default synthpop method CART to obtain the synthetic datasets      ##
##########################################################################################

# All data is synthesized by means of the "CART" default method.
out_cart <- future_map_dfr(1:nsim, function(x) {data <- normal(r2, ratio, rho, n1)$dat
                                                normal_syn(data, formula = f, pop.inf = T)},
                           .id = "sim", 
                           .progress = T, 
                           .options = future_options(seed = as.integer(123)))

# Obtain a summary of the results (this are results previously obtained already).
summary_out_cart <- out_cart %>% filter(Method == "Real_Sample" | Method == "Syn10") %>%
  print_results(., real_coefs)

# Specify a small function for inside the future_map commands
synth_sampled_data <- function(p, r2, ratio, rho, n, formula, pop.inf = T, method = NULL, M) {
  part <- normal(r2, ratio, rho, n)$dat %>% resample_partition(p)
  syn_part_data(partitioned_data = part, M = M, formula = formula, pop.inf = pop.inf, method = method)
}


# Specify the number of partitions (5 equally large partitions)
p <- c(d1 = .2, d2 = .2, d3 = .2, d4 = .2, d5 = .2)

normal(r2,ratio, rho, n1)$dat %>% resample_partition(p)

# Sample data with n = 100, so 5 partitions of twenty persons, synthesize data by means of the 
# cart method
out_cart_part_n100 <- future_map_dfr(1:nsim, ~ synth_sampled_data(p = p, r2 = r2, ratio = ratio, rho = rho, 
                                                                  n = n1, formula = f, pop.inf = T, M = 10),
                                .id = "sim", .progress = T, .options = future_options(seed = as.integer(123)))
# Obtain the results
summary_out_cart_part_n100 <- print_results(out_cart_part_n100, coefs = real_coefs)

# Set the sample size to 1000
n2 <- 1000
# Sample data with n = 1000, so 5 partitions of 200 persons, synthesize data by means of the 
# cart method
out_cart_part_n1000 <- future_map_dfr(1:nsim, ~ synth_sampled_data(p = p, r2 = r2, ratio = ratio, rho = rho, 
                                                                   n = n2, formula = f, pop.inf = T, M = 10),
                                      .id = "sim", .progress = T, .options = future_options(seed = as.integer(123)))
# Obtain results
summary_out_cart_part_n1000 <- print_results(out_cart_part_n1000, coefs = real_coefs)

# Set the sample size to 10000
n3 <- 10000
# Sample data with n = 10000, so 5 partitions of 2000 persons, synthesize data by means of the 
# cart method
out_cart_part_n10000 <- future_map_dfr(1:nsim, ~ synth_sampled_data(p = p, r2 = r2, ratio = ratio, rho = rho, 
                                                                   n = n3, formula = f, pop.inf = T, M = 10),
                                      .id = "sim", .progress = T, .options = future_options(seed = as.integer(123)))

summary_out_cart_part_n10000 <- print_results(out_cart_part_n10000, coefs = real_coefs)



##########################################################################################
## Since we know that the data is generated by means of a multivariate normal mechanism ##
## we now use a normal model to synthesize the data (that is, the first variable is     ##
## randomly drawn from a normal distribution, and all other variables are regression on ##
## the previously synthesized variables by means of linear regression).                 ##
##########################################################################################

# Change the method from NULL to "norm"
norm <- rep("norm", length(ratio) + 1)

# Sample data with n = 100, so 5 partitions of twenty persons, synthesize data by means of the 
# normal linear regression/random draws from a normal distribution
out_norm_part_n100 <- future_map_dfr(1:nsim, ~ synth_sampled_data(p = p, r2 = r2, ratio = ratio, rho = rho, 
                                                                  n = n1, formula = f, pop.inf = T, 
                                                                  method = norm, M = 10),
                                     .id = "sim", .progress = T, .options = future_options(seed = as.integer(123)))
# Obtain results
summary_out_norm_part_n100 <- print_results(out_norm_part_n100, coefs = real_coefs)

# Sample data with n = 1000, so 5 partitions of 200 persons, synthesize data by means of the 
# normal linear regression/random draws from a normal distribution
out_norm_part_n1000 <- future_map_dfr(1:nsim, ~ synth_sampled_data(p = p, r2 = r2, ratio = ratio, rho = rho, 
                                                                   n = n2, formula = f, pop.inf = T, 
                                                                   method = norm, M = 10),
                                      .id = "sim", .progress = T, .options = future_options(seed = as.integer(123)))

# Obtain results
summary_out_norm_part_n1000 <- print_results(out_norm_part_n1000, coefs = real_coefs)

# Sample data with n = 10000, so 5 partitions of 2000 persons, synthesize data by means of the 
# normal linear regression/random draws from a normal distribution
out_norm_part_n10000 <- future_map_dfr(1:nsim, ~ synth_sampled_data(p = p, r2 = r2, ratio = ratio, rho = rho, 
                                                                   n = n3, formula = f, pop.inf = T, 
                                                                   method = norm, M = 10),
                                      .id = "sim", .progress = T, .options = future_options(seed = as.integer(123)))


summary_out_norm_part_n10000 <- print_results(out_norm_part_n10000, coefs = real_coefs)















# out_same_part <- future_map_dfr(1:nsim, function(x) syn_part_data(part, M = 5, formula = wgt ~ hgt + age, pop.inf=F),
#                       .id = "sim", .progress = T, .options = future_options(seed = as.integer(123)))
# 
# out_nsim_parts <- future_map_dfr(1:nsim, function(x) {part <- resample_partition(boyscomp, partitions)
#                                                       syn_part_data(part, M = 5, formula = wgt ~ hgt + age, pop.inf=F)},
#                                  .id = "sim", .progress = T, .options = future_options(seed = as.integer(123)))
# 
# boyscoefs <- coef(lm(wgt ~ hgt + age, data = boyscomp))
# 
# summary_out_same_part <-  print_results(out_same_part, coefs = boyscoefs)
# summary_out_nsim_parts <- print_results(out_nsim_parts, coefs = boyscoefs)

