##########################################################################################
## Simulate multivariate normal data, partition it, and synthesize the partitions,      ##
## then, bind the synthetic partitions and analyse it                                   ##
##########################################################################################

## Source the completed boys data, and source the functions file
source("1.a Create data - boys complete.R")
source("1.c Functions.R")

## Load the required packages, furrr for parallel map functions, tidyverse for tidy data,
## synthpop for data synthesis
library(furrr)
library(tidyverse)
library(synthpop)

## Specify that we run the code in multiple sessions, to speed up the process
plan(multisession)

## Set the number of simulations
nsim <- 1000

## Specify the input for the multivariate normal data sampling
r2 <- .5                    # R2 of .5
ratio <- c(0,1,2)           # Uninformative predictor and two informative predictors
rho <- diag(length(ratio))  # Uncorrelated predictors
n1 <- 100                   # Sample size
n2 <- 1000
#n3 <- 10000

# real_coefs are the population regression coefficients
real_coefs <- normal(r2,ratio,rho,n1)$coefs

# f is the formula of the linear regressions during the rest of the code
f <- DV ~ -1 + IV1 + IV2 + IV3

##########################################################################################
## First, we use the default synthpop method CART to obtain the synthetic datasets      ##
##########################################################################################


# Specify a small function for inside the future_map commands
synth_sampled_data <- function(p, r2, ratio, rho, n, formula, pop.inf = T, method = NULL, M) {
  part <- normal(r2, ratio, rho, n)$dat %>% resample_partition(p)
  syn_part_data(partitioned_data = part, M = M, formula = formula, pop.inf = pop.inf, method = method)
}


# Specify the number of partitions (5 equally large partitions)
n.parts <- 10
p <- rep(1 / n.parts, n.parts)
names(p) <- paste0("p", 1:n.parts)


# Sample data with n = 100, so 5 partitions of twenty persons, synthesize data by means of the 
# cart method
p10_out_cart_part_n100 <- future_map_dfr(1:nsim, ~ synth_sampled_data(p = p, r2 = r2, ratio = ratio, rho = rho, 
                                                                      n = n1, formula = f, pop.inf = T, M = 10),
                                         .id = "sim", .progress = T, .options = future_options(seed = as.integer(123)))
p10_out_cart_part_n1000 <- future_map_dfr(1:nsim, ~ synth_sampled_data(p = p, r2 = r2, ratio = ratio, rho = rho, 
                                                                       n = n2, formula = f, pop.inf = T, M = 10),
                                          .id = "sim", .progress = T, .options = future_options(seed = as.integer(123)))
# p10_out_cart_part_n10000 <- future_map_dfr(1:nsim, ~ synth_sampled_data(p = p, r2 = r2, ratio = ratio, rho = rho, 
#                                                                         n = n3, formula = f, pop.inf = T, M = 10),
#                                            .id = "sim", .progress = T, .options = future_options(seed = as.integer(123)))


# Obtain the results
p10_summary_out_cart_part_n100 <- print_results(p10_out_cart_part_n100, coefs = real_coefs)
p10_summary_out_cart_part_n1000 <- print_results(p10_out_cart_part_n1000, coefs = real_coefs)
# p10_summary_out_cart_part_n10000 <- print_results(p10_out_cart_part_n10000, coefs = real_coefs)



##########################################################################################
## Since we know that the data is generated by means of a multivariate normal mechanism ##
## we now use a normal model to synthesize the data (that is, the first variable is     ##
## randomly drawn from a normal distribution, and all other variables are regression on ##
## the previously synthesized variables by means of linear regression).                 ##
##########################################################################################

# Change the method from NULL to "norm"
norm <- rep("norm", length(ratio) + 1)

# Sample data with n = 100, so 5 partitions of twenty persons, synthesize data by means of the 
# normal linear regression/random draws from a normal distribution
p10_out_norm_part_n100 <- future_map_dfr(1:nsim, ~ synth_sampled_data(p = p, r2 = r2, ratio = ratio, rho = rho, 
                                                                      n = n1, formula = f, pop.inf = T, 
                                                                      method = norm, M = 10),
                                         .id = "sim", .progress = T, .options = future_options(seed = as.integer(123)))
p10_out_norm_part_n1000 <- future_map_dfr(1:nsim, ~ synth_sampled_data(p = p, r2 = r2, ratio = ratio, rho = rho, 
                                                                       n = n2, formula = f, pop.inf = T, 
                                                                       method = norm, M = 10),
                                          .id = "sim", .progress = T, .options = future_options(seed = as.integer(123)))
# p10_out_norm_part_n10000 <- future_map_dfr(1:nsim, ~ synth_sampled_data(p = p, r2 = r2, ratio = ratio, rho = rho, 
#                                                                         n = n3, formula = f, pop.inf = T, 
#                                                                         method = norm, M = 10),
#                                            .id = "sim", .progress = T, .options = future_options(seed = as.integer(123)))

# Obtain results
p10_summary_out_norm_part_n100 <- print_results(p10_out_norm_part_n100, coefs = real_coefs)
p10_summary_out_norm_part_n1000 <- print_results(p10_out_norm_part_n1000, coefs = real_coefs)
# p10_summary_out_norm_part_n10000 <- print_results(cor_out_norm_part_n10000, coefs = real_coefs)


##########################################################################################
## Now do the same with correlated data                                                 ##
##########################################################################################

rho_cor <- rho
rho_cor[lower.tri(rho_cor)] <- rho_cor[upper.tri(rho_cor)] <- c(.15,.25,.35)

# real_coefs are the population regression coefficients
real_coefs_cor <- normal(r2,ratio,rho_cor,n1)$coefs

# Sample data with n = 100, so 5 partitions of twenty persons, synthesize data by means of the 
# cart method
cor_p10_out_cart_part_n100 <- future_map_dfr(1:nsim, ~ synth_sampled_data(p = p, r2 = r2, ratio = ratio, rho = rho_cor, 
                                                                      n = n1, formula = f, pop.inf = T, M = 10),
                                         .id = "sim", .progress = T, .options = future_options(seed = as.integer(123)))
cor_p10_out_cart_part_n1000 <- future_map_dfr(1:nsim, ~ synth_sampled_data(p = p, r2 = r2, ratio = ratio, rho = rho_cor, 
                                                                       n = n2, formula = f, pop.inf = T, M = 10),
                                          .id = "sim", .progress = T, .options = future_options(seed = as.integer(123)))
# cor_p10_out_cart_part_n10000 <- future_map_dfr(1:nsim, ~ synth_sampled_data(p = p, r2 = r2, ratio = ratio, rho = rho_cor, 
#                                                                         n = n3, formula = f, pop.inf = T, M = 10),
#                                            .id = "sim", .progress = T, .options = future_options(seed = as.integer(123)))


# Obtain the results
cor_p10_summary_out_cart_part_n100 <- print_results(cor_p10_out_cart_part_n100, coefs = real_coefs_cor)
cor_p10_summary_out_cart_part_n1000 <- print_results(cor_p10_out_cart_part_n1000, coefs = real_coefs_cor)
# cor_p10_summary_out_cart_part_n10000 <- print_results(cor_p10_out_cart_part_n10000, coefs = real_coefs_cor)



##########################################################################################
## Since we know that the data is generated by means of a multivariate normal mechanism ##
## we now use a normal model to synthesize the data (that is, the first variable is     ##
## randomly drawn from a normal distribution, and all other variables are regression on ##
## the previously synthesized variables by means of linear regression).                 ##
##########################################################################################

# Change the method from NULL to "norm"
norm <- rep("norm", length(ratio) + 1)

# Sample data with n = 100, so 5 partitions of twenty persons, synthesize data by means of the 
# normal linear regression/random draws from a normal distribution
cor_p10_out_norm_part_n100 <- future_map_dfr(1:nsim, ~ synth_sampled_data(p = p, r2 = r2, ratio = ratio, rho = rho_cor, 
                                                                      n = n1, formula = f, pop.inf = T, 
                                                                      method = norm, M = 10),
                                         .id = "sim", .progress = T, .options = future_options(seed = as.integer(123)))
cor_p10_out_norm_part_n1000 <- future_map_dfr(1:nsim, ~ synth_sampled_data(p = p, r2 = r2, ratio = ratio, rho = rho_cor, 
                                                                       n = n2, formula = f, pop.inf = T, 
                                                                       method = norm, M = 10),
                                          .id = "sim", .progress = T, .options = future_options(seed = as.integer(123)))
# cor_p10_out_norm_part_n10000 <- future_map_dfr(1:nsim, ~ synth_sampled_data(p = p, r2 = r2, ratio = ratio, rho = rho_cor, 
#                                                                         n = n3, formula = f, pop.inf = T, 
#                                                                         method = norm, M = 10),
#                                            .id = "sim", .progress = T, .options = future_options(seed = as.integer(123)))

# Obtain results
cor_p10_summary_out_norm_part_n100 <- print_results(cor_p10_out_norm_part_n100, coefs = real_coefs_cor)
cor_p10_summary_out_norm_part_n1000 <- print_results(cor_p10_out_norm_part_n1000, coefs = real_coefs_cor)
# cor_p10_summary_out_norm_part_n10000 <- print_results(cor_p10_out_norm_part_n10000, coefs = real_coefs_cor)
