---
title: "ADS Thesis simulation"
author: 
- Thom Volker
- Utrecht University
date: "`r format(Sys.time(), '%d-%m-%Y')`"
output: 
  html_document:
    theme: spacelab
    highlight: tango
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages

```{r, results = F, message = F}
library(mice)
library(tidyverse)
library(furrr)
library(magrittr)
library(knitr)
```

# Read in the data

```{r}
data_url <- "https://raw.githubusercontent.com/gerkovink/Synthetic_ADS/main/Data/diabetes.csv"
data <- read_csv(url(data_url), 
                 col_types = cols(Pregnancies = col_integer(), 
                                  Glucose = col_integer(), 
                                  BloodPressure = col_integer(), 
                                  SkinThickness = col_integer(), 
                                  Insulin = col_integer(), 
                                  Age = col_integer(), 
                                  Outcome = col_factor(levels = c("0", "1"))))
```

# True model

```{r}
fit <- glm(Outcome ~ BMI + Glucose + Pregnancies, 
           family = binomial(link = "logit"), 
           data = data)

coef(fit)
sqrt(diag(vcov(fit)))
broom::tidy(fit)
```

# Synthetic data model

```{r}
mod1 <- c(Pregnancies              = "pmm", 
          Glucose                  = "norm", 
          BloodPressure            = "norm", 
          SkinThickness            = "pmm", 
          Insulin                  = "pmm", 
          BMI                      = "norm", 
          DiabetesPedigreeFunction = "pmm", 
          Age                      = "pmm", 
          Outcome                  = "logreg.boot")

mod2 <- c(Pregnancies              = "cart", 
          Glucose                  = "cart", 
          BloodPressure            = "cart", 
          SkinThickness            = "cart", 
          Insulin                  = "cart", 
          BMI                      = "cart", 
          DiabetesPedigreeFunction = "cart", 
          Age                      = "cart", 
          Outcome                  = "cart")

pred <- make.predictorMatrix(data)
```

# Simulate

```{r, cache = TRUE, cache.lazy = FALSE}
nsim <- 500
plan(multisession)
```

```{r, cache = TRUE, cache.lazy = FALSE}
syn2_maxit1 <- future_map(1:nsim, function(x) {
  data %>%
    mice(m = 5, 
         maxit = 1,
         method = mod2,
         predictorMatrix = pred,
         where = matrix(TRUE, nrow(.), ncol(.)),
         print = FALSE)
}, .options = future_options(seed = as.integer(123)), .progress = FALSE)
```

```{r, cache = TRUE, cache.lazy = FALSE}
syn2_cp_maxit1 <- future_map(1:nsim, function(x) {
  data %>%
    mice(m = 5, 
         maxit = 1,
         method = mod2,
         predictorMatrix = pred,
         where = matrix(TRUE, nrow(.), ncol(.)),
         cp = 1e-32,
         minbucket = 3,
         print = FALSE)
}, .options = future_options(seed = as.integer(123)), .progress = FALSE)
```

# Source functions file for pooling

```{r}
source("~/Documents/Federated_imputation/mice_synthesizing/simulations/functions.R")
```

# Synthetic data estimates

```{r, include = F}
library(kableExtra)
```


```{r}
syn2_maxit1 %>%
  map(function(x) {
    x %$% 
      glm(Outcome ~ BMI + Glucose + Pregnancies, 
          family = binomial(link = "logit"))
    }) %>%
  map_dfr(pool3.syn) %>%
  ci_cov(., fit) %>%
  kable(digits = 3) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

```{r}
syn2_cp_maxit1 %>%
  map(function(x) {
    x %$% 
      glm(Outcome ~ BMI + Glucose + Pregnancies, 
          family = binomial(link = "logit"))
    }) %>%
  map_dfr(pool3.syn) %>%
  ci_cov(., fit) %>%
  kable(digits = 3) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

```{r, cache = TRUE, cache.lazy = FALSE}
syn2_boot <- future_map(1:nsim, function(x) {
  data[sample(1:nrow(data), replace = TRUE), ] %>%
    mice(m = 10, 
         maxit = 1,
         method = mod2,
         predictorMatrix = pred,
         where = matrix(TRUE, nrow(.), ncol(.)),
         cp = 0.0001,
         minbucket = 3,
         print = FALSE)
}, .options = future_options(seed = as.integer(123)), .progress = FALSE)

syn2_cp_boot <- future_map(1:nsim, function(x) {
  data[sample(1:nrow(data), replace = TRUE), ] %>%
    mice(m = 5, 
         maxit = 1,
         method = mod2,
         predictorMatrix = pred,
         where = matrix(TRUE, nrow(.), ncol(.)),
         cp = 1e-32,
         minbucket = 3,
         print = FALSE)
}, .options = future_options(seed = as.integer(123)), .progress = FALSE)

true_fits <- map(1:nsim, ~glm(Outcome ~ BMI + Glucose + Pregnancies,
                 family = binomial(link = "logit"), data = data[sample(1:nrow(data), replace = TRUE),]))

map_dfr(true_fits, function(x) {
  x %>% broom::tidy(conf.int = TRUE) %>% mutate(cov = conf.low < coef(fit) & coef(fit) < conf.high)
}) %>% 
  group_by(term) %>%
  summarise(est = mean(estimate),
                 se  = mean(std.error),
                 ciw = mean(conf.high - conf.low),
                 cov = mean(cov)) %>%
  kable(digits = 3) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

syn2_boot %>%
     map(function(x) {
    x %$% 
      glm(Outcome ~ BMI + Glucose + Pregnancies, 
          family = binomial(link = "logit"))
    }) %>%
  map_dfr(pool3.syn) %>%
  ci_cov(., fit) %>%
  kable(digits = 3) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

syn2_cp_boot %>%
   map(function(x) {
    x %$% 
      glm(Outcome ~ BMI + Glucose + Pregnancies, 
          family = binomial(link = "logit"))
    }) %>%
  map_dfr(pool3.syn) %>%
  ci_cov(., fit) %>%
  kable(digits = 3) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

# Zero's replaced by imputation

```{r, cache=TRUE, cache.lazy=FALSE}
data.imp <- 
  data %>%
  lapply(FUN = function(x) {
  ifelse(is.numeric(x) & x == 0, NA, x)
  }) %>%
  as.data.frame() %>%
  mutate(Outcome = factor(Outcome, labels = c("0", "1"))) %>%
  mice(m = 1, maxit = 50, method = "pmm") %>%
  complete()

fit.imp <- glm(Outcome ~ BMI + Glucose + Pregnancies,
               family = binomial(link = "logit"),
               data = data.imp)

syn2.boot.imp <- future_map(1:nsim, function(x) {
  data.imp[sample(1:nrow(data.imp), replace = TRUE), ] %>%
    mice(m = 10, 
         maxit = 1,
         method = mod2,
         predictorMatrix = pred,
         where = matrix(TRUE, nrow(.), ncol(.)),
         cp = 0.0001,
         minbucket = 3,
         print = FALSE)
}, .options = future_options(seed = as.integer(123)), .progress = FALSE)

syn2.cp.boot.imp <- future_map(1:nsim, function(x) {
  data.imp[sample(1:nrow(data.imp), replace = TRUE), ] %>%
    mice(m = 10, 
         maxit = 1,
         method = mod2,
         predictorMatrix = pred,
         where = matrix(TRUE, nrow(.), ncol(.)),
         cp = 1e-32,
         minbucket = 3,
         print = FALSE)
}, .options = future_options(seed = as.integer(123)), .progress = FALSE)

true.fits.imp <- map(1:nsim, ~glm(Outcome ~ BMI + Glucose + Pregnancies,
                                  family = binomial(link = "logit"), 
                                  data = data.imp[sample(1:nrow(data.imp), replace = TRUE),]))

true.fits.imp %>%
  map_dfr(function(x) {
    x %>% 
    broom::tidy(conf.int = TRUE) %>% 
    mutate(cov = conf.low < coef(fit.imp) & coef(fit.imp) < conf.high)
  }) %>% 
  group_by(term) %>%
  summarise(est = mean(estimate),
                 se  = mean(std.error),
                 ciw = mean(conf.high - conf.low),
                 cov = mean(cov)) %>%
  kable(digits = 3) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

syn2.boot.imp %>%
  map(function(x) {
    x %$% 
      glm(Outcome ~ BMI + Glucose + Pregnancies, 
          family = binomial(link = "logit"))
    }) %>%
  map_dfr(pool3.syn) %>%
  ci_cov(., fit.imp) %>%
  kable(digits = 3) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

syn2.cp.boot.imp %>%
  map(function(x) {
    x %$% 
      glm(Outcome ~ BMI + Glucose + Pregnancies, 
          family = binomial(link = "logit"))
    }) %>%
  map_dfr(pool3.syn) %>%
  ci_cov(., fit.imp) %>%
  kable(digits = 3) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```


